'use server';

/**
 * @fileOverview This file defines a Genkit flow that provides contextual follow-up questions
 * based on the user's initial responses to gather more detailed home design requirements.
 *
 * - provideContextualFollowUp - An async function that takes user input and returns follow-up questions.
 * - ProvideContextualFollowUpInput - The input type for the provideContextualFollowUp function.
 * - ProvideContextualFollowUpOutput - The output type for the provideContextualFollowUp function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ProvideContextualFollowUpInputSchema = z.object({
  userInput: z.string().describe('The user input to analyze and generate follow-up questions for.'),
  conversationHistory: z.string().describe('The previous conversation history.'),
});
export type ProvideContextualFollowUpInput = z.infer<typeof ProvideContextualFollowUpInputSchema>;

const ProvideContextualFollowUpOutputSchema = z.object({
  followUpQuestions: z.string().describe('The follow-up questions generated by the AI.'),
});
export type ProvideContextualFollowUpOutput = z.infer<typeof ProvideContextualFollowUpOutputSchema>;

export async function provideContextualFollowUp(input: ProvideContextualFollowUpInput): Promise<ProvideContextualFollowUpOutput> {
  return provideContextualFollowUpFlow(input);
}

const prompt = ai.definePrompt({
  name: 'provideContextualFollowUpPrompt',
  input: {schema: ProvideContextualFollowUpInputSchema},
  output: {schema: ProvideContextualFollowUpOutputSchema},
  prompt: `You are an AI Architect Assistant, and your goal is to help users design their dream home.

You will generate thoughtful follow-up questions based on the user's input to clarify their requirements and offer helpful design suggestions.
Consider the previous conversation history to maintain context.

User Input: {{{userInput}}}

Conversation History: {{{conversationHistory}}}

Based on the user input and conversation history, generate a list of follow-up questions to gather more details about their dream home.
Explain WHY certain details matter for design.
Build excitement about their future home, and use architectural terminology naturally.
`,
});

const provideContextualFollowUpFlow = ai.defineFlow(
  {
    name: 'provideContextualFollowUpFlow',
    inputSchema: ProvideContextualFollowUpInputSchema,
    outputSchema: ProvideContextualFollowUpOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
